### ISSUE TITLE
Multiple User Selector  Attributes Per User

### ISSUE THREAD

**Issue by drumrby** [concrete5cojp/addon_user_selector_attribute#3]
I am using this attribute to attach 2 different users to a user. For instance, a member of a site has to have two other members sponsor them for membership in the site.

When I create 2 user selector attributes, both uniquely named it only lets me select a user in one of the attributes. If I try to select a user in the both, I get a "Null UserInfo" error in one of the attributes. It appears you can only select one user per user, file or page, wherever the attribute is assigned.

Any help you can provide would be greatly appreciated!

**Comment by drumrby** [comment]
First, I enabled the user selector attribute to be used as an user attribute. Then create two new user attributes using the user selector attribute. The first attribute’s handle is sponsor1 the second attribute’s handle is sponsor2. I enabled “show on public profile” and “show on registration form” on both attributes. Then I to a member of the site and tried to set the sponsor1 attribute. When I select a user and it returns me to the member, the sponsor1 attribute is blank and the user I selected shows up under the sponsor2 attribute. If I Now click the check mark on sponsor2 it sets the user selected. But the. If I got back and try to select another user for sponsor1 that is when I get the error, and it will not let me select any user.

**Comment by katzueno** [comment]
Oh ok.
Thx!

You were using as user attribute! I was only planning to be used as page/files/express attributes.

OK I'll try to take a look.
(But I have to tell you that it it lower priority task for us.)

**Comment by drumrby** [comment]
Ok. Just so you know, I also tried adding multiple user selector attributes to a page, and it behaved the exact same way. Thank you!

**Comment by katzueno** [comment]
OK. Got it.

**Comment by drumrby** [comment]
Any progress on this? I really need to get this implemented soon and haven't been able to figure out the issue on my own.

**Comment by katzueno** [comment]
@drumrby 
Sorry no progress, yet.
We haven't encountered any projects that requires multiple user selector attribute yet.
If we have some paying project with multiple attribute requirement, we will escalate the priority.

**Comment by katzueno** [comment]
@drumrby 
OK.
I will have my engineer take a look how many hours it may take.

Can you send me an email to info at concrete5.co.jp
OR https://concrete5.co.jp/contact

We will send you a quote.

Question:

Which one do you prefer?

- Having single attribute and ability to select multiple users
- Two attributes to attach single users.

**Comment by katzueno** [comment]
@drumrby Waiting for your answer.

**Comment by katzueno** [comment]
@drumrby OK.

Since I haven't heard back from you, I am stopping to care this issue now until you contact us.

**Comment by drumrby** [comment]
@katzueno Sent you an email last week just wanted to make sure it came through. Sorry for the delay I was out of the office for a little while.

**Comment by katzueno** [comment]
@drumrby Thx.

We received your email.
We started to take a look at it.
Will respond back to you via email.
